// <auto-generated />
using System;
using ComicAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191123065408_DB_first")]
    partial class DB_first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicAPI.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre_name");

                    b.HasKey("GenreID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            Genre_name = "Trinh Thám"
                        },
                        new
                        {
                            GenreID = 2,
                            Genre_name = "Ngôn Tình"
                        },
                        new
                        {
                            GenreID = 3,
                            Genre_name = "Viễn Tưởng"
                        },
                        new
                        {
                            GenreID = 4,
                            Genre_name = "Xuyên Không"
                        },
                        new
                        {
                            GenreID = 5,
                            Genre_name = "Dị Giới"
                        });
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComicId");

                    b.Property<string>("Content");

                    b.Property<int>("STT");

                    b.Property<string>("Title");

                    b.HasKey("ChapterID");

                    b.HasIndex("ComicId");

                    b.ToTable("Chapter");

                    b.HasData(
                        new
                        {
                            ChapterID = 1,
                            ComicId = 1,
                            Content = "",
                            STT = 1,
                            Title = "Đỗ Mạnh Cầm"
                        },
                        new
                        {
                            ChapterID = 2,
                            ComicId = 1,
                            Content = "",
                            STT = 2,
                            Title = "Khổ luyện"
                        },
                        new
                        {
                            ChapterID = 3,
                            ComicId = 2,
                            Content = "",
                            STT = 1,
                            Title = "Bộ mặt thật của 3 bà chị"
                        },
                        new
                        {
                            ChapterID = 4,
                            ComicId = 2,
                            Content = "",
                            STT = 2,
                            Title = "Xui Kiếp"
                        });
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.Comic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<int>("Chapter_long");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int>("Likes");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<DateTime>("Update_time");

                    b.Property<int>("Views");

                    b.HasKey("ID");

                    b.ToTable("Comic");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Đỗ Cầm",
                            Chapter_long = 0,
                            Description = " Sẽ thế nào khi bạn mang trong người song tu thần kinh? Sở hữu khả năng xuyên qua 10 thế giới? Đào hoa vận không thua gì Rito (To love ru)? Lập 1 giàn harem, thủy tinh cung khủng nhất vũ trụ về khoe cho bọn bạn gato chơi.Đỗ Cầm có tất cả nhưng lại thừa 1 điều..... thừa bóng ma tâm lý về phụ nữ.Hãy đón xem công cuộc bị chinh phục của anh chàng đen đủi hay may mắn này nhé",
                            Image = "https://sstruyen.com/assets/img/story//cong-cuoc-bi-em-gai-chinh-phuc.jpg",
                            Likes = 100,
                            Name = "Công Cuộc Bị 999 Em Gái Chinh Phục",
                            Status = 0,
                            Update_time = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Views = 100
                        },
                        new
                        {
                            ID = 2,
                            Author = "Phong Tử Tam Tam",
                            Chapter_long = 0,
                            Description = "Cố Minh Sâm giúp Ôn Vãn, lại không ngờ con bé kia lấy oán trả ơn.Mà Ôn Vãn không thẹn với lòng, dám khẳng định: Cô đối với Cố Minh Sâm, chỉ còn kém việc, dâng cái mạng nhỏ này cho anh ta. Kết quả chỉ đổi lấy tờ giấy thỏa thuận li hôn. Quả nhiên, thế giới này vô cùng bất công, người tốt lại chẳng được đền đáp.Dùng một câu để chốt văn án: Kết thúc đoạn hôn nhân hữu danh vô thực  đáng thất vọng, vận đào hoa của Ôn Vãn bỗng nhiên khởi sắc.",
                            Image = "https://sstruyen.com/assets/img/story//cau-chuyen-ho-o.jpg",
                            Likes = 100,
                            Name = "Câu Chuyện Hồ Đồ",
                            Status = 0,
                            Update_time = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Views = 100
                        });
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.ComicGenre", b =>
                {
                    b.Property<int>("ComicID");

                    b.Property<int>("GenreID");

                    b.HasKey("ComicID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("ComicGenre");

                    b.HasData(
                        new
                        {
                            ComicID = 1,
                            GenreID = 2
                        },
                        new
                        {
                            ComicID = 1,
                            GenreID = 1
                        },
                        new
                        {
                            ComicID = 2,
                            GenreID = 5
                        },
                        new
                        {
                            ComicID = 2,
                            GenreID = 3
                        });
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "user@gmail.com",
                            Password = "12345",
                            Role = 0,
                            Username = "ThuNguyen"
                        },
                        new
                        {
                            ID = 2,
                            Email = "user@gmail.com",
                            Password = "12345",
                            Role = 0,
                            Username = "NhutThuy"
                        },
                        new
                        {
                            ID = 3,
                            Email = "user@gmail.com",
                            Password = "12345",
                            Role = 0,
                            Username = "TuongVi"
                        },
                        new
                        {
                            ID = 4,
                            Email = "admin@gmail.com",
                            Password = "12345",
                            Role = 1,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.Chapter", b =>
                {
                    b.HasOne("ComicAPI.Models.Entities.Comic", "Comic")
                        .WithMany("Chapters")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ComicAPI.Models.Entities.ComicGenre", b =>
                {
                    b.HasOne("ComicAPI.Models.Entities.Comic", "Comic")
                        .WithMany("ComicGenres")
                        .HasForeignKey("ComicID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComicAPI.Genre", "Genre")
                        .WithMany("ComicGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
